openfoodfacts/search-a-licious

app/api.py
app/models/request.py
app/scripts/http_autocomplete_query.py
app/scripts/http_search_query.py
app/test/test_api.py

- Implementation of the main search (ie, facet search, not auto-complete). 
- Also includes a few minor changes to the proposed API.
- Includes Tests for Autocomplete
Tests for the facet search will come in a follow-up PR.
Since folks are on vacation, I'll merge this PR tomorrow even without approval (have confirmed with Stephane that this is okay), but please comment if you don't want that to happen.

Facet search query + Autocomplete testing

---

.pre-commit-config.yaml
Dockerfile
README.md
app/api.py
app/import_queue/queue_manager.py
app/import_queue/redis_client.py
app/models/product.py
app/models/request.py
app/product.schema.json
app/scripts/data-fields.txt
app/scripts/generate_product_from_data_fields.py
app/scripts/http_search_query.py
app/scripts/perform_import.py
app/scripts/write_to_redis.py
app/utils/constants.py
app/utils/response.py
docker-compose.yml
requirements.txt

Redis implementation:
- Reader thread + data structures
- Script to test populate Redis
- Associated docker changes
- Little tweaks to the product - making the code required, and be the _id field, meaning that updates will work nicely when this is all connected
- Import script now retrieves the writes from the past 24 hours
As always, since folks are on vacation, I'll merge this tomorrow.

Redis implementation

---

.github/workflows/release-please.yml

- ci: auto-generate changelog based on semantic PRs

ci: auto-generate changelog based on semantic PRs

---

.github/workflows/semantic-pr.yml

ci: enforce semantic-pr

---

.github/workflows/auto-assign-pr.yml

ci:Auto-assign new PRs

---

.env
README.md
app/import_queue/product_client.py
app/import_queue/queue_manager.py
app/models/product.py
app/scripts/http_autocomplete_query.py
app/scripts/http_search_query.py
docker-compose.yml

- Improves documentation
- Allows configuration of different URLs for querying the OFF API
- Switches to the default network, which was validated in testing
See corresponding server PR: https://github.com/openfoodfacts/openfoodfacts-server/pull/7239

feat: Set network dynamically + docker improvements

---

.env
README.md
docker-compose.yml
docker/dev.yml

Some improvement in the docker-compose configuration.

build: improving docker-compose configuration

---

docker-compose.yml

We can simplify this file by:
- Removing the cert logic. We don't need to worry about that since we're in a closed ecosystem here (and, there's no sensitive data in the first place)
- Removing volumes, etc - whole setup piece
I did have to update the health check though. Have confirmed that this works with a partial local import after running this.

feat: Simplify docker

---

.github/workflows/pre-commit.yml

- Add server side check of pre-commit hooks
see: https://github.com/pre-commit/action

ci: add pre-commit checks

---

app/scripts/http_autocomplete_query.py
app/scripts/http_search_query.py

minor: Removed unnecessary ES connection in scripts (enables running with only standard libs installed).

refactor: remove unecessary ES connection in helper scripts

---

app/api.py
app/import_queue/queue_manager.py
app/scripts/write_to_redis.py
docker-compose.yml
docker/dev.yml

This is a more robust approach.
@simonj2 I think the thread architecture was really fragile for something important to monitor in production.

feat: make queue manager a standalone process

---

.github/workflows/container-deploy.yml
app/import_queue/queue_manager.py

Fix some variables + avoid using secrets when there is no need for it.
Part of:
- #28

ci: Deploy fix variables

---

README.md

search-a-licious is changing direction a bit to be a more generic engine.

docs: link to new architecture document

---

.github/workflows/container-build.yml
.github/workflows/container-deploy.yml
CODEOWNERS
docker-compose.yml

ci: change service name

---

.pre-commit-config.yaml
app/config.py
app/indexing.py
app/taxonomy.py
app/utils/__init__.py
app/utils/io.py
poetry.lock
pyproject.toml
tests/unit/data/openfoodfacts_config.yml
tests/unit/test_indexing.py
tests/unit/test_query.py

Also add better documentation and unit tests.

feat: add support for synonyms for taxonomy field types

---

.github/workflows/container-deploy.yml

Configure REDIS_HOST for production.

chore: add redis host for production

---

Makefile
README.md
app/_import.py
docs/install.md

Docker compose V2 is now the default, V1 is legacy.

fix: switch docker compose v2

---

frontend/README.md
frontend/public/off.html

Add some CSS to off.html to verify styling is possible and make it demo-able.

feat: some CSS

---

.env
.env.openfoodfacts
.github/workflows/container-deploy.yml
.github/workflows/pre-commit.yml
README.md
app/api.py
docker-compose.yml

- Change CORS from api to allow js queries 
- https://github.com/openfoodfacts/search-a-licious/issues/80

feat: Change CORS headers to allow JS queries

---

Makefile

Add _ensure_network dependencies to make up command

fix: add ensure_network to make up command

---

frontend/README.md

- update frontend/README.md to add informations about the new components

docs: update frontend/README.md

---

frontend/src/mixins/search-ctl.ts
frontend/src/search-autocomplete.ts
frontend/src/search-checkbox.ts
frontend/src/search-radio.ts
frontend/src/search-toggle.ts

- fix undefined pageSize
- fix z-index of search-autocomplete 
- avoid checkbox, radio and toggle to wrap

fix: add some frontend fixes

---

frontend/public/off.html
frontend/src/css/header.ts
frontend/src/css/index.ts
frontend/src/css/utils.ts
frontend/src/icons/search.ts
frontend/src/mixins/search-ctl.ts
frontend/src/mixins/suggestion-selection.ts
frontend/src/search-a-licious.ts
frontend/src/search-bar.ts
frontend/src/search-button.ts
frontend/src/test/search-bar_test.ts
frontend/src/test/search-button_test.ts
frontend/xliff/fr.xlf

feat: update search bar to add "Search" text to encourage the user to search and add reset button

---

frontend/src/mixins/search-ctl.ts
frontend/src/search-bar.ts
frontend/src/search-facets.ts
frontend/src/utils/enums.ts

- update search-bar to show text when term is selected
- update reset button to reset all filters including facets

feat: update search-bar

---

.gitignore
.pre-commit-config.yaml
frontend/Dockerfile
frontend/package.json

- Copy `generated` files to `public` to allow bundle to import it dynamically

fix: i18n are not loaded because is dynamically import

---

.github/workflows/container-deploy.yml
Makefile

ci: sync scripts on deploy

---

frontend/src/utils/charts.ts

fix: move docs and fix content

---

frontend/public/off.html

I added the src="https://world.openfoodfacts.org/images/icons/dist/packaging.svg" as a default image in off.html

feat: add default images for products without image in off.html #208

---

docker-compose.yml

We really need to be sure we restart at server startup. This seems not to be completely the case.

build: better restart policy for docker

---

README.md
docs/users/explain-query-language.md

A small first doc on query language…

docs: how to use query language

---

app/api.py
frontend/public/index.html

It's more universal for other projects re-using search-a-licious.

chore: use index.html instead of off.html

---

app/_import.py

chore: single process import

---

app/config.py
app/indexing.py
data/config/openfoodfacts.yml
tests/int/data/test_off.yml
tests/unit/conftest.py
tests/unit/data/openfoodfacts_config.yml
tests/unit/data/test_mapping.json
tests/unit/test_config.py
tests/unit/test_indexing.py
tests/unit/test_query.py

fixes:
- #237 
Also added the "nested" type (not thoroughly tested)

feat: adding sub fields to object

---

mkdocs.yml

ci: docs quick improvements

---

.env
.env.openfoodfacts
.github/workflows/container-deploy.yml
.github/workflows/pre-commit.yml
docs/devs/how-to-install.md

- Limit CORS access in **development** and **test** environments to **localhost**
- Allow CORS access in **staging** and **production** environments from **all origins**
- #80

feat: Allow CORS access from all origins

---

app/openfoodfacts.py

See https://github.com/openfoodfacts/openfoodfacts-server/pull/11818 for more details about the schema changes.
There was also a bug in `build_image_fields` method, in which the `fields` variable was returned before we iterate over all image keys, this fixes it.

fix: always convert `images` field to legacy schema

---

app/openfoodfacts.py
tests/unit/test_openfoodfacts.py

fix: fix brand taxonomy preprocessor after schema update

---

crowdin.yml

- ci: Update crowdin.yml to add locale disambiguation for language with variants, typically Dutch in the current translation PR

ci: Update crowdin.yml to add locale disambiguation for language with variants
